export const PROJECTS_DATA = {
  'first-year': [
    {
      name: 'Eco-Sort Smart Bin',
      icon: '♻️',
      year: '2024',
      tags: ['IoT', 'AI', 'Hardware'],
      shortDesc: 'Automatic waste segregation using real-time image recognition.',
      problemStatement: 'Improper waste segregation at the source leads to severe recycling inefficiencies and environmental harm, with over 60% of recyclables ending up in landfills.',
      solutionOverview: 'An IoT-enabled bin using real-time image recognition to automatically sort waste into recyclable, organic, and hazardous compartments using a Raspberry Pi and a trained CNN model.',
      techStack: ['Raspberry Pi', 'Google Coral', 'Python', 'React', 'TensorFlow Lite', 'OpenCV'],
      teamMembers: [
        { name: 'Noah Evans', role: 'Hardware Engineer', initials: 'NE', color: '#10b981' },
        { name: 'Olivia Garcia', role: 'ML Engineer', initials: 'OG', color: '#a855f7' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Metal Soda Can', output: 'Recyclable Compartment Activated', badge: 'Metal Detect Sensor' },
        { input: 'Banana Peel', output: 'Organic Compartment Activated', badge: 'CNN Image Model' },
        { input: 'Lithium Battery', output: 'Hazardous Compartment Activated', badge: 'Chemical Warning Sensor' },
      ],
      // Add images/videos here: { type: 'image'|'video', src: '/media/...', poster?: '...', caption?: '...' }
      media: [],
    },
    {
      name: 'IoT Smart Plant Waterer',
      icon: '💧',
      year: '2024',
      tags: ['IoT', 'Arduino', 'Automation'],
      shortDesc: 'Automated plant watering triggered by soil moisture sensors.',
      problemStatement: 'Houseplants frequently wither when owners travel or forget to water them on schedule, costing millions in replacements annually.',
      solutionOverview: 'A simple Arduino-based soil moisture monitoring system that triggers an automated micro-pump when dryness threshold is detected, with remote override via Bluetooth.',
      techStack: ['Arduino', 'C++', 'Soil Sensors', 'Micro-pump', 'Bluetooth LE'],
      teamMembers: [
        { name: 'Emma Watson', role: 'Embedded Systems', initials: 'EW', color: '#f59e0b' },
        { name: 'Rupert Grint', role: 'App Developer', initials: 'RG', color: '#ef4444' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Dry Soil (Moisture 15%)', output: 'Pump Relay Enabled (Watering for 5s)', badge: 'Analog Moisture Pin' },
        { input: 'Wet Soil (Moisture 85%)', output: 'Pump Idle (Adequate Water levels)', badge: 'Saturate Indicator' },
      ],
      media: [],
    },
    {
      name: 'Campus Energy Monitor',
      icon: '⚡',
      year: '2024',
      tags: ['Web', 'Analytics', 'IoT'],
      shortDesc: 'Real-time energy usage dashboard for campus buildings.',
      problemStatement: 'Campus administrators lack real-time visibility into energy usage patterns, leading to significant wastage and high electricity bills.',
      solutionOverview: 'A networked smart-meter system with a React dashboard providing real-time energy analytics, historical trends, and anomaly alerts for department administrators.',
      techStack: ['React', 'Node.js', 'MQTT', 'InfluxDB', 'Grafana', 'Raspberry Pi'],
      teamMembers: [
        { name: 'Arjun Mehta', role: 'Full-Stack Dev', initials: 'AM', color: '#06b6d4' },
        { name: 'Priya Singh', role: 'Data Analyst', initials: 'PS', color: '#8b5cf6' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Peak Afternoon Lecture Block', output: 'Alert: High AC usage flagged (Auto Setback applied)', badge: 'MQTT Broker Node' },
        { input: 'Mid-Night Downtime Scan', output: 'No-waste steady stream (3.2 kW background)', badge: 'Admin Threshold' },
      ],
      media: [],
    },
  ],
  'mini': [
    {
      name: 'SMARTAPPROVE – AI Document Approval System',
      icon: '⚡',
      year: '2026',
      tags: ['Agentic AI', 'LangGraph', 'Gemini', 'Django', 'React (Vite)', 'Workflows'],
      shortDesc: 'Agentic AI platform digitizing & validating academic approvals with multi-agent workflows.',
      problemStatement: 'Manual academic approvals for bonafide certificates and internships are paper-heavy, slow, and inconsistent. ERPs lack document intelligence to automatically extract details, check policies, or route requests.',
      solutionOverview: 'SMARTAPPROVE is an Agentic AI-based workflow automation platform. AI agents automatically extract information from document uploads, validate them against institutional policies with explainable feedback, and route requests through a stateful multi-stage approval hierarchy with human-in-the-loop oversight.',
      techStack: ['React (Vite)', 'Django', 'LangGraph', 'Google Gemini', 'PostgreSQL / SQLite', 'REST APIs'],
      teamMembers: [
        { name: 'Abinaya S', role: 'AI & Data Lead', initials: 'AS', color: '#6366f1' },
        { name: 'Chandrakanth R M', role: 'Backend & Workflow Dev', initials: 'CR', color: '#10b981' },
        { name: 'Manish V', role: 'Full-Stack Developer', initials: 'MV', color: '#f59e0b' },
        { name: 'Ponmanoj P', role: 'Agent Architecture Lead', initials: 'PP', color: '#ec4899' },
        { name: 'Sneha Rajesh', role: 'Frontend & UI/UX', initials: 'SR', color: '#06b6d4' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Bonafide PDF Certificate Upload', output: 'Extraction Agent: Name, Roll No, Dept & Reason extracted (94% Accuracy)', badge: 'PyMuPDF + LLM' },
        { input: 'Audit Agent Policy Check', output: 'Passed: Valid passport purpose & signature verified', badge: 'LangGraph Multi-Agent' },
        { input: 'Stateful Workflow Route', output: 'Routed: Tutor Approved → Program Co-ordinator In Review', badge: 'Stateful RBAC' },
      ],
      media: [
        {
          type: 'image',
          src: '/images/smartapprove/architecture_poster.jpg',
          caption: 'SmartApprove Poster: System Architecture, Multi-Agent Pipeline & Evaluation Metrics (94% Accuracy, 90% Admin Time Saved)',
        },
        {
          type: 'image',
          src: '/images/smartapprove/request_modal.jpg',
          caption: 'Incoming Request Validation Modal: AI extraction checklist, document matching & explainable feedback',
        },
        {
          type: 'image',
          src: '/images/smartapprove/approval_chain.jpg',
          caption: 'Student Request Dashboard: Real-time Multi-Stage Approval Chain tracking (Tutor → Program Co-ord → HOD → Office → Dean)',
        },
      ],
    },
  ],
  'capstone': [
    {
      name: 'AI Crop Disease Predictor',
      icon: '🌱',
      year: '2024',
      tags: ['Computer Vision', 'Drone', 'AI'],
      shortDesc: 'Drone-based CNN system predicting crop diseases weeks in advance.',
      problemStatement: 'Farmers suffer massive crop losses due to late detection of plant diseases before visual symptoms appear, resulting in billions in agricultural losses annually.',
      solutionOverview: 'A drone-based image capture system paired with a CNN model to predict diseases weeks in advance from subtle leaf discolorations invisible to the naked eye.',
      techStack: ['Python', 'TensorFlow', 'React', 'AWS EC2', 'OpenCV', 'DJI SDK', 'PostgreSQL'],
      teamMembers: [
        { name: 'Ivy Kim', role: 'ML Research Lead', initials: 'IK', color: '#10b981' },
        { name: 'Jack Martinez', role: 'Drone Systems', initials: 'JM', color: '#6366f1' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Scan Sector 4 (Maize crop)', output: 'Early Stage Anthracnose risk detected (Score 84%)', badge: 'Drone CNN Inference' },
        { input: 'Crop Leaf Sample #419', output: 'Healthy chlorophyll indices logged', badge: 'RGB Index' },
      ],
      media: [],
    },
    {
      name: 'Decentralized Voting System',
      icon: '🗳️',
      year: '2024',
      tags: ['Blockchain', 'Web3', 'Security'],
      shortDesc: 'Blockchain-based e-voting for transparent university elections.',
      problemStatement: 'Current electronic voting systems are vulnerable to tampering and lack transparent verification mechanisms for voters to verify their own votes.',
      solutionOverview: 'A blockchain-based e-voting platform ensuring anonymous, verifiable, and immutable votes using smart contracts on Ethereum, with a user-friendly Next.js frontend.',
      techStack: ['Solidity', 'Ethereum', 'Next.js', 'Web3.js', 'IPFS', 'MetaMask'],
      teamMembers: [
        { name: 'Liam Brown', role: 'Blockchain Dev', initials: 'LB', color: '#6366f1' },
        { name: 'Mia Chen', role: 'Frontend Dev', initials: 'MC', color: '#ec4899' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Submit Ballot ID #3911', output: 'Ballot verified. Block Hash: 0x5a18c... added', badge: 'Solidity Contract' },
        { input: 'Check Ballot Status', output: 'Ballot Status: Complete. Immutable hash locked.', badge: 'MetaMask Gateway' },
      ],
      media: [],
    },
  ],
  'hackathon': [
    {
      name: 'MedConnect Disaster Relief',
      icon: '🏥',
      year: '2024',
      tags: ['BLE Mesh', 'Offline-first', 'Emergency'],
      shortDesc: 'Offline Bluetooth-mesh app for disaster victim mapping.',
      problemStatement: 'During natural disasters, centralized cellular networks collapse, preventing emergency responders from locating victims or coordinating relief efforts.',
      solutionOverview: 'A decentralized Bluetooth-mesh messaging app that maps victim locations and medical statuses without any internet connection, syncing when connectivity resumes.',
      techStack: ['Flutter', 'BLE Mesh API', 'SQLite', 'Node.js', 'Dart', 'OpenStreetMap'],
      teamMembers: [
        { name: 'Alex Mercer', role: 'Mobile Lead', initials: 'AM', color: '#f59e0b' },
        { name: 'Clara Oswald', role: 'BLE Systems', initials: 'CO', color: '#10b981' },
      ],
      demoLink: 'https://example.com',
      simulatedPayloads: [
        { input: 'Broadcast SOS Beacon', output: 'Beacon caught by Node 3 (Distance 12m). Added to Grid', badge: 'BLE Hardware Mesh' },
        { input: 'Pull Offline Maps Sync', output: 'Synchronized local mapping coordinates successfully', badge: 'SQLite Offline Db' },
      ],
      media: [],
    },
  ],
};
